apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend-service
  labels:
    app: {{ .Release.Name }}-backend-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend-service
    spec:
      containers:
      - name: {{ .Chart.Name }}-backend-service
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 9080
        env:
          - name: MONGO_CONN_STR
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: MONGO_CONN_STR
{{/*            value: mongodb://{{ .Release.Name }}-mongodb:27017/{{ .Values.mongodb.auth.database }}*/}}
          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: MONGO_USERNAME
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: MONGO_PASSWORD