apiVersion: v2
name: backend
description: A Helm chart for the backend application
version: 0.1.0
dependencies:
- name: mongodb
  version: 7.x.x
  repository: https://charts.bitnami.com/bitnami