replicaCount: 1
image:
  repository: terak8dock/appfrontend
  pullPolicy: IfNotPresent
  tag: "1.0.0"
service:
  type: ClusterIP
  port: 8080

mongodb:
  auth:
    enabled: true
    rootPassword: rootpass
    username: user
    password: password
    database: mydatabase