replicaCount: 1
image:
  repository: terak8dock/appbackend
  pullPolicy: IfNotPresent
  tag: "1.0.0"
service:
  type: ClusterIP
  port: 9080

mongodb:
  auth:
    enabled: true
    rootPassword: rootpass
    username: db_user
    password: Secret_db_password
    database: dynamicky_nazov_db